name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
      - name: "Unit tests"
        run: nimble test -y
      - name: "Integration tests"
        run: nimble integration
